### PR TITLE
Support connecting with a unix domain socket

### PR DESCRIPTION
**Pull request by Ramblurr**
As discussed in  #285

This changes the semantics of `--server` (or the env var, etc) to `--server <IP/FQDN | /path/to/socket>`

### CODE REVIEW

**Review by deitch — CHANGES_REQUESTED** [review]
Thanks again for putting this in.

A few comments:

1. The docs should be updated, specifically the main README and `docs/configuration.md`
2. We should have some kind of test for this, even just a unit test of `Connection.MySQL()`
3. Should `--port` be deprecated, and everything move into `--server`? So you can do `--server 127.0.01:3306` or `--server 127.0.0.1` or `--server /path/to/unix`, and `--port will be ignored?

**Comment by Ramblurr** [comment]
>     1. The docs should be updated, specifically the main README and `docs/configuration.md`

Done! 


>     2. We should have some kind of test for this, even just a unit test of `Connection.MySQL()`

I'm afraid I'm not much a go-lang user myself so I don't feel comfortable adding this, would you be able to add the test?  (If there was already a similar test I could modify it).

>     3. Should `--port` be deprecated, and everything move into `--server`? So you can do `--server 127.0.01:3306` or `--server 127.0.0.1` or `--server /path/to/unix`, and `--port will be ignored?

I don't think that's necessary. Port is already optional, and this change preserves that. Since the go-sql-driver does accept `Addr` as `host:port`, it could be done.

I leave that decision up to you as the maintainer.

**Comment by Ramblurr** [comment]
I've enabled the "Allow edits by maintainers" feature so feel free to push to my branch if you want.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
This looks good to me. I won't be able to add enough for the testing for the next week at least, and don't want to hold it up. Existing testing should catch any errors for current functionality, and unix-domain socket is new, so I am good with that.

I approved it. Anything else you want before we merge it in?

**Pull request merged**
