### PR TITLE
Upgrade GitHub Actions version for CI, Release & Deploy

### PR DESCRIPTION
**Pull request by jonathandreyer**
Hello,

I have seen some warnings about versions into Actions logs, and then I have upgraded all versions of GitHub Actions. Unfortunately, I cannot test it on my fork, so that is the reason for the draft PR (I hope that will allow running CI workflows).

Best,

Jonathan Dreyer

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Thanks, just moved to ready and kicked off CI. Let's let it run.

**Comment by jonathandreyer** [comment]
> Thanks, just moved to ready and kicked off CI. Let's let it run.

I've seen that the CI & Deploy pipelines work well (on the PR & on the master commit). However, the Release pipeline has not been tested (which is expected behavior). Maybe it will be a good thing to test it with a "new release" to be sure that work as expected.

**Comment by deitch** [comment]
Agreed. A new release should be out soon. Might even be the last release candidate.

**Comment by deitch** [comment]
Just cut v1.0.0-rc6, looks pretty happy. Another few minutes, will be complete.

Close to v1.0.0.

**Pull request merged**
