### PR TITLE
Restore single database

### PR DESCRIPTION
**Pull request by silane**
Currently, the docker image has no way to restore a database saved with the option `SINGLE_DATABASE=true`. This pull request makes it possible.

Specify `SINGLE_DATABASE=true` and `DB_NAMES` variable along with `DB_RESTORE_TARGET` to restore a single database to the database named `DB_NAMES`. `DB_NAMES` is expected to contain one database name, not space-separated multiple database names despite its plural variable name.

Implementation of #121.

### CODE REVIEW

**Comment by deitch** [comment]
This makes sense, thanks for adding it. The README needs to be updated, though.

**Comment by silane** [comment]
I updated README about this feature.

**Comment by silane** [comment]
Are there anything I can do?

**Comment by deitch** [comment]
Not at all, I didn't see the alert that you had updated the README.

Is there any reason to have both `DB_NAMES` and `SINGLE_DATABASE`? Why would it not work if the logic is: if `DB_NAMES` is empty, restore all; else, restore just the named ones.

The logic might be something like:

```bash
   DBDATABASE=
    if [ -n "$DB_NAMES"  ]; then
       DBDATABASE="-D$DB_NAMES"
   fi
```

**Comment by silane** [comment]
That should work too.
The reason why I didn't do so is that I thought having same option when restoring and saving is simpler and prevents wrong usage.

**Comment by deitch** [comment]
OK, good point. I see it now. Yeah, we should be consistent. Maybe we should clean both up, but we can worry about that a different time.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Strange that CI didn't run, and I don't see anywhere to restart it.

**Comment by deitch** [comment]
I don't know why CI didn't run, and will not restart. 

I just merged in a PR that supports local testing on Mac, and with M1 support, not just Linux/amd64. So I now can run it locally anywhere. I clicked the "Update Branch", which is kicking off CI again, hopefully will be fine this time.

**Pull request merged**
