### PR TITLE
Fix parsing begin time flag

### LINKED ISSUE #267: Go version: parsing of `begin` time fails
## Expected Behavior
Passing a 4 digit start time to the `begin` flag should work.

## Current Behavior
mysql-backup exits with an error

`ERRO[0000] error creating timer: invalid format for begin delay '0915': <nil> `

## Steps to Reproduce
on master branch:
`./mysql-backup dump --target /backup --begin 0915`

## Possible Solution
The regex for the begin flag in timer.go, checks for >3 matching groups, but there are only 3. Example 0915, matching groups 0915, 09, 15
Change the check to >2

## Possible Implementation
pkg/core/timer.go:83 change to:
```go
	case len(startTimeParts) > 2:
```

### PR DESCRIPTION
**Pull request by FluffyEscargot**
Closes #267 
- Parsing of start time failed, because regex produces 3 matching groups, not more

### CODE REVIEW

**Review by deitch — CHANGES_REQUESTED** [review]
1. Can we split this into 2 changes? Based on the comment on the issue, the discussion around "how to fix date parsing which is broken" is distinct from the discussion around "how to support timezones".
2. Can we include a test for this? We already have [TestWaitForCron()](https://github.com/databacker/mysql-backup/blob/master/pkg/core/timer_test.go#L8) which was the most important part to get right, given its complexities), so this should be easy enough to add. More importantly, it will help explain the use cases here.

**Comment by FluffyEscargot** [comment]
I've added the tests to cover basic cases, not looking at timezones yet.
What I haven't included yet, is some inputs which pass, even though they shouldn't in my opinion:
```go
{"fail invalid time", "2401", "2018-10-10T10:00:00Z", time.Duration(0), fmt.Errorf("invalid format for begin delay '2401'")},
{"fail too long time", "12345", "2018-10-10T10:00:00Z", time.Duration(0), fmt.Errorf("invalid format for begin delay '12345'")},
```
1.  `2401`, time.Date accepts values outside the usual range, so doesn't have to be <24 and <60 for hours and minutes
2. `12345`, the regex currently allows for leading or trailing characters, so `aaaa2309bbbb` also passes. Adding `^` and `$` to begin and end of the regex would fix that

**Comment by deitch** [comment]
> I've added the tests to cover basic cases, not looking at timezones yet.

Thanks. Keeps it cleaner. 

> What I haven't included yet, is some inputs which pass, even though they shouldn't in my opinion:

So I should wait to kick off CI?

**Comment by FluffyEscargot** [comment]
Ready to merge

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
All looks good, but needs a rebase.

**Review by deitch — APPROVED** [review]

**Pull request merged**
