### PR TITLE
Automatically Removes backups that are over X days old

### PR DESCRIPTION
**Pull request by j-flowers**
Added a function that runs at the end of the loop to check for back ups that are older that x amount of days, and removes them automatically. 

Use the env DB_DUMP_ARCHIVE_DAYS_TO_KEEP to set the number of days to keep. 

If this variable is not set, backups are kept indefinitely.

### CODE REVIEW

**Comment by deitch** [comment]
Thanks for this. 

First, it really needs documentation. Anything that can delete things needs to be clear on what and when it will do so, and what the limitations are, so people are comfortable.

Second, and more fundamentally, I have been quite hesitant about this for quite some time. On the one hand, people want it. On the other hand, it mixes backup with delete in a single run. Would it not be better if it were a separate run? It can be the same container image, but run in a separate mode, just like backup and restore are 2 separate modes?

**Comment by waynehaffenden** [comment]
Any update on this?

**Comment by deitch** [comment]
Nothing that I have seen. Someone needs to add in documentation, and break it out so it is run in a separate mode, separate process.

**Comment by leranp** [comment]
this is a great option to add to this docker

**Comment by vulkanosaure** [comment]
Really expecting that option too, not sure if i can use that image otherwise

**Comment by NapoSky** [comment]
Bump this PR. It should be mandatory to avoid custom scripts to make the clean with it :)

**Comment by deitch** [comment]
No one has touched it since originally opened. I would take it based on my suggestions, but that needs to be done. And a rebase.

**Comment by outofnames** [comment]
The deletion could be added as a post processing script instead of a environment variable. It would be more explicit and the user can customise it to their needs.

**Comment by deitch** [comment]
I am going to close this. It is over a year old (actually more than that), and the go-based version is coming to replace it; v1.0.0-rc1 already is out, -rc2 in a few days.

But pre- and post-processing scripts continue to be supported in the new version, which creates options.

If someone can show how this would work in the go version, what the UX would be and how it fits, it is worth a new issue.

**Pull request closed without merging**
