### PR TITLE
Make once, cron and begin/frequency flags mutually exclusive

### LINKED ISSUE #265: Go version: Mutually exclusive flags check not working
## Expected Behavior
Supplying just the `--cron` flag or just the `--once` flag should work.

## Current Behavior
mysql-backup exits with errors depending on the flag

`ERRO[0000] error creating timer: option 'Cron' is exclusive and must not be used with Begin, Once or Frequency`

`ERRO[0000] error creating timer: option 'Once' is exclusive and must not be used with Begin, Cron or Frequency`

## Steps to Reproduce
on master branch:
`./mysql-backup dump --target /backup --cron "0 0 * * *"`
`./mysql-backup dump --target /backup --once`

via docker:
`docker run -e DB_DUMP_TARGET=/backup -e DB_DUMP_CRON="0 0 * * *" databack/mysql-backup:1.0.0-rc2 dump`
`docker run -e DB_DUMP_TARGET=/backup -e DB_DUMP_ONCE=true databack/mysql-backup:1.0.0-rc2 dump`

## Possible Solution
The `--begin`and `--frequency` flags have defaults (`+0` and `1440`) which are loaded at the time when mutually exclusive flags are checked. Instead, check if both flags are set, before defaults are loaded.

## Possible Implementation
cmd/dump.go:229 add:
```go
	cmd.MarkFlagsMutuallyExclusive("once", "cron")
	cmd.MarkFlagsMutuallyExclusive("once", "begin")
	cmd.MarkFlagsMutuallyExclusive("once", "frequency")
	cmd.MarkFlagsMutuallyExclusive("cron", "begin")
	cmd.MarkFlagsMutuallyExclusive("cron", "frequency")
```
pkg/core/timer.go:44 remove:
```go
	// validate we do not have conflicting options
	if opts.Once && (opts.Cron != "" || opts.Begin != "" || opts.Frequency != 0) {
		return nil, errors.New("option 'Once' is exclusive and must not be used with Begin, Cron or Frequency")
	}

	if opts.Cron != "" && (opts.Begin != "" || opts.Frequency != 0) {
		return nil, errors.New("option 'Cron' is exclusive and must not be used with Begin, Once or Frequency")
	}
```

### PR DESCRIPTION
**Pull request by FluffyEscargot**
Closes #265 

Changes:
- Make the flags themselves mutually exclusive and remove check in timer.go. This check always failed when using cron, as the begin and frequency options are populated with defaults.
- add else if for timer creation, to prevent overwriting cron delay with `begin +0` delay from default

### CODE REVIEW

**Review by deitch — COMMENTED** [review]
Is it possible to extend the simple CLI flag tests in [dump_test.go](https://github.com/databacker/mysql-backup/blob/master/cmd/dump_test.go) to test for these exclusions?

The entire test's purpose is to ensure that flags behave the way they expect to, and then call (or do not, if in error) the correct func afterwards.

**Comment by FluffyEscargot** [comment]
> Is it possible to extend the simple CLI flag tests in [dump_test.go](https://github.com/databacker/mysql-backup/blob/master/cmd/dump_test.go) to test for these exclusions?
> 
> The entire test's purpose is to ensure that flags behave the way they expect to, and then call (or do not, if in error) the correct func afterwards.

Sure, I'll try that

**Comment by FluffyEscargot** [comment]
Added passing and error tests for the flags. Should be ready for merge

One thing I noticed while writing the tests, is that the `dbconn` variable of the root command seems to be persistent between tests (cmd/root.go:35).
So moving the "config file" testcase to the top, crashes the test cases below, as the values for user, password, etc. are still set. I just put my tests in an order that works.

**Comment by deitch** [comment]
> One thing I noticed while writing the tests, is that the dbconn variable of the root command seems to be persistent between tests (cmd/root.go:35).

Sure, because it is a global CLI flag, so it needs to be set in root in `PersistentPreRunE`.

> So moving the "config file" testcase to the top, crashes the test cases below, as the values for user, password, etc. are still set. I just put my tests in an order that works

Oh, interesting. That should be fixed. But let's do it after this one.

Looks like this needs a rebase?

**Comment by deitch** [comment]
> So moving the "config file" testcase to the top, crashes the test cases below, as the values for user, password, etc. are still set

I am not sure I get this. The value of `dbconn` is used in `DumpOptions`. Those are set and passed explicitly in each test case, so why should the broader `dbconn` matter?

**Comment by FluffyEscargot** [comment]
> > So moving the "config file" testcase to the top, crashes the test cases below, as the values for user, password, etc. are still set
> 
> I am not sure I get this. The value of `dbconn` is used in `DumpOptions`. Those are set and passed explicitly in each test case, so why should the broader `dbconn` matter?

No, the executable uses the global `dbconn` variable, which just gets continously updated with each test (first its empty, then host: "abc", then host:"abc", port:"3306", user:...). The dump options passed to the test are just to compare against the options used by the function.
I think one option of solving it, would be to reset it before adding any values
cmd/root.go:91 + dbconn = database.Connection{}

**Comment by deitch** [comment]
I stumbled across a similar issue when working on a different PR, and realized it is the same root cause. I fixed it in an almost-ready PR #277 . It should be completely fixed there.

**Review by deitch — APPROVED** [review]

**Pull request merged**
