### PR TITLE
bug/mysqlclient

### LINKED ISSUE #105: mysqldump with generated column doesn't work while importing
I am getting below error when importing mysqldump taken from this docker image.

`ERROR 3105 (HY000) at line 82: The value specified for generated column 'column_name' in table 'table_name' is not allowed.`

Source and destination mysql server having same version.

MySQL server version:

`mysqld Ver 5.7.26 for Linux on x86_64 (MySQL Community Server (GPL))`

MySQL Dump client version:

`mysqldump Ver 10.17 Distrib 10.3.12-MariaDB, for Linux (x86_64)`

### PR DESCRIPTION
**Pull request by ToshY**
Fixes #105

### CODE REVIEW

**Comment by ToshY** [comment]
@deitch It fails on `make test_dump` but it doesn't show much debug output in the CI. Can't debug this locally myself as either the SMB ports are already in use for me. Could you take a look at it?

**Review by deitch — COMMENTED** [review]
This is not going to help. There is no mysql-client in `apk` repositories. It is just a dummy package pointing to mariadb client.

See even [the latest](https://pkgs.alpinelinux.org/package/v3.15/main/x86_64/mysql-client)

**Comment by ToshY** [comment]
Ah indeed, apologies. But that still leaves me with a bit of confusing, as I build an image with `mysql-client` and tested it, and I didn't get the generated virtual columns anymore. So maybe updating the version would make a difference? I'll test this later again tonight.

**Comment by deitch** [comment]
I am confused as well

**Comment by deitch** [comment]
> It fails on make test_dump but it doesn't show much debug output in the CI. Can't debug this locally myself as either the SMB ports are already in use for me. Could you take a look at it?

Yes, it looks like more recent versions of mysql take a _lot_ longer to start up. I extended the startup wait time and added `DEBUG` to test logs in an open PR. If that passes, we can merge in and you can rebase on it.

**Comment by dabico** [comment]
Just wondering, what is the status of this PR? Will it ever get merged? I'm currently having problems with generated columns as described in #105.

**Comment by deitch** [comment]
I will comment there. I am going to close this one, as the bash-based is becoming legacy.

**Pull request closed without merging**
